version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/bar/lib/mysql

    restart: always
# used if container get stopped by mistakely and doesn't have exit status 0 then it automatically restart the container

    environment:
      - MYSQL_ROOT_PASSWORD=anypass
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  
  wordpress:

  # this wordpress depends on db service
    depends_on:
      - db
    
    image: wordpress:latest

    ports:
      - "8000:80"

    restart: always

    environment:
      - WORDRESS_DB_HOST=3306
      - WORDRESS_DB_USER=wordpress
      - WORDRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

volumes:
  db_data: {}